declare function run(): string;
declare var fun2: () => number;
declare function getinfo(name: string, age: number): any;
declare var getinfo1: (name: string, age: number) => any;
declare function NoRet(): void;
declare var getinfo2: (name: string, age?: number | undefined) => any;
declare var getinfo2: (name: string, age?: number | undefined) => any;
declare function sum(...result: number[]): number;
declare function getInfor(str: string): string;
declare function getInfor(str: number): string;
